### ISSUE TITLE
Schema update or create with Sf5

### ISSUE THREAD

**Issue by avieyto** [trikoder/oauth2-bundle#196]
I am receiving this exception running doctrine:schema:update --force

[Doctrine\DBAL\Schema\SchemaException (30)]
There is no column with name 'userIdentifier' on table 'oauth2_access_token'.

I am using Symfony 5.0.7

**Comment by spideyfusion** [comment]
Fixed with https://github.com/trikoder/oauth2-bundle/pull/197. This is caused by the different Doctrine naming strategy used in new installations of Symfony 5.x:

https://github.com/symfony/recipes/blob/2de05e19f916c8841102f2a35f0dc08dbac219ed/doctrine/doctrine-bundle/2.0/config/packages/doctrine.yaml#L10

It seems that Doctrine doesn't apply any naming strategy when defining indexes in your mapping configuration.
