### ISSUE TITLE
Support for OpenId Connect

### ISSUE THREAD

**Issue by MichaelKubovic** [trikoder/oauth2-bundle#25]
Hello, there is already a decent implementation of OIDC support for the thephpleague/oauth2-server here https://github.com/steverhoades/oauth2-openid-connect-server

I'd be happy to work on a MR that integrates it as a optional dependency if it's something you'd consider to merge.

Also, I'd need #18 and related PRs merged in order to start, thanks!

**Comment by ajgarlag** [comment]
I'm already working on adding support for OIDC on top of #18 but still not sure if it should be integrated here, or distributed in another bundle. You can see my `feature/openid-connect` branch in https://github.com/ajgarlag/oauth2-bundle/tree/feature/openid-connect.

@spideyfusion Are you interested in this feature?

**Comment by MichaelKubovic** [comment]
@ajgarlag continuing debate from https://github.com/trikoder/oauth2-bundle/pull/18#issuecomment-461394916

Which event would you like to listen to, to trigger authentication?

**Comment by easybi-hj** [comment]
Any updates on this?

**Comment by DevNiko** [comment]
@MichaelKubovic 
Possibly is the this [Bundle](oauth2-openid-connect-server) a solution for you. I have implemented it in my project. A Combination of Trikoder oAuth2 Server, Leage oAuth2 Server and the oauth2-openid-connect-server.
But notice, that the oauth2-openid-connect-server does not support the newest version of the Leage oAuth Server Bundle. Because of Breaking Changes.

**Comment by MichaelKubovic** [comment]
Thank you @DevNiko. We decided to move integration closer to our project source as it was exhausting to maintain open-source fork with features we didn't need ourselves. Thanks for the bundle anyway, someone may find it useful.
