### ISSUE TITLE
Question: does this bundle support all the PHP OAuth 2.0 Server features?

### ISSUE THREAD

**Issue by thePhrenologist** [trikoder/oauth2-bundle#66]
Hi, thanks for this bundle.

Does it support these league/oauth2-server features:

- Authorization code grant
- JWT
- PKCE

**Comment by ddlzz** [comment]
hi! so did you find out how to enable PKCE using the bundle? I'm currently struggling with this myself

**Comment by florianajir** [comment]
> hi! so did you find out how to enable PKCE using the bundle? I'm currently struggling with this myself
> 
> in league/oauth2-server I found `AuthCodeGrant::enableCodeExchangeProof()` but so far can't figure out how to call it correctly

I opened an issue https://github.com/trikoder/oauth2-bundle/issues/138 to ask about the PKCE functionality as I'm struggling too

**Comment by ddlzz** [comment]
yes, I did. in phpleague/oauth-server:v8.0 the PCKE check is on by default when a client passes the `code_chanllenge` param: https://oauth2.thephpleague.com/upgrade-guide/

so since the PR https://github.com/trikoder/oauth2-bundle/pull/139 was merged into master yesterday, you could set `"trikoder/oauth2-bundle": "dev-master#8becc18"` in the require section of your composer.json config just like I did. or you could wait for the new release version depending on the urgency of your situation
